image: php:8.1

cache:
  paths:
    - vendor/

before_script:
  - apt-get update -yqq
  - apt-get install -yqq git
  - apt-get install unzip
  - curl -sS https://getcomposer.org/installer | php
  - mv composer.phar /usr/local/bin/composer
  - composer install

stages:
  - test
  - code_quality

phpunit:
  stage: test
  script:
    - ./bin/phpunit

phpcs:
  stage: code_quality
  script:
    - ./vendor/bin/phpcs
  allow_failure: true

phpstan:
  stage: code_quality
  script:
    - ./vendor/bin/phpstan analyse
  allow_failure: true